#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "testing and building your code before commiting"

yarn run check-lint || {
    echo "Linting failed, please fix the errors before commiting"
    false;
}

yarn run check-types || {
    echo "Typescript type checking failed, please fix the errors before commiting"
    false;
}

yarn run build || {
    echo "Build failed, please fix the errors before commiting"
    false;
}

echo "All checks passed, you can commit now"